### ISSUE TITLE
sc's basic command don't work

### ISSUE THREAD

**Issue by alexandre-mbm** [n-t-roff/sc#19]
![sc-dont-work](https://user-images.githubusercontent.com/957501/100238297-c967c200-2f0e-11eb-9e2d-5c47413f985a.png)

Typed:
```
=
3
[RETURN]
```

**Comment by n-t-roff** [comment]
Is this reproducible? I cannot confirm this behavior.

**Comment by alexandre-mbm** [comment]
I tried it on Android 5.1 by using Termux.

**Comment by Arumes** [comment]
Termux went through some big changes since 2020, and [requires Android 7 now](https://github.com/termux/termux-app?tab=readme-ov-file#installation). Support for Android 5 was officially dropped on 01-01-2020, well before this issue was opened.

On my old tablet (2016) with Android 8 and the latest sc version from package n-t-roff-sc in the [current Main repository](https://github.com/termux/termux-packages/wiki/Mirrors#primary-host), I cannot reproduce this issue.
