### ISSUE TITLE
Where is the Windows fork, for this

### ISSUE THREAD

**Issue by GHExplorer** [n-t-roff/sc#23]
Hi,

I keep reading mentions about a Windows port of SC, but cannot locate it anywhere.

The two version mentioned here

http://www.bttr-software.de/freesoft/dbase.htm#spreadsheet

are sc and slsc.

Is it possible the Windows version is no longer available?

**Comment by Arumes** [comment]
The SC version mentioned there was not a Windows version, but MS-DOS. As you can see, the 32 bit version didn't even run on Windows. I doubt if the SC developers of those days were responsible for the executable, because it's more common to provide the source code only.

SLSC was a fork, a derivative. The SC developers were not involved.

In any case, there's no executable available unless you can find it elsewhere and are willing to trust that .exe... My advice is to get the code and try compiling it yourself.

**Comment by Arumes** [comment]
@dtkerns Another close request... :-) I'd say this question is answered, and I suppose you're not planning to provide a Windows executable. I'm still fairly new to this system, so if I'm wrong: what's the reason to keep this issue open?

**Comment by Arumes** [comment]
I guess nowadays if you compile it in something like Powershell, you call it a Windows port, because MS-DOS is no longer a thing. So in theory the Wikipedia article should still be correct, but I can't check if it actually compiles because I haven't touched Windows in the last 20 years.

Thanks for replying and closing the issue though. :-)
