### ISSUE TITLE
What license can this sc fork be distributed as?

### ISSUE THREAD

**Issue by claes** [n-t-roff/sc#28]
As the original Gosling version was public domain (i.e not copyleft), I am unsure if this fork is public domain as well. Can the license it can be distributed under be clarified?

**Comment by n-t-roff** [comment]
I had expected that there would be a ISC license, but you are right, the license file is missing. So lets say it has the same license as the original version.

**Comment by Arumes** [comment]
@dtkerns 
Could you put this in a LICENSE file so we can close this issue? It's a standard text for public domain projects, ofcourse you can modify it as you see fit.

--- 8< --- cut here --- 8< --- cut here --- 8< --- cut here --- 8< ---
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <https://unlicense.org>
--- 8< --- cut here --- 8< --- cut here --- 8< --- cut here --- 8< ---
